---
apiVersion: batch/v1
kind: Job
metadata:
  name: atlas-omop-db-reset
spec:
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      serviceAccountName: jenkins-service
      containers:
        - name: fix
          image: quay.io/cdis/awshelper:master
          imagePullPolicy: Always
          env:
            - name: gen3Env
              valueFrom:
                configMapKeyRef:
                  name: global
                  key: environment
            - name: DB_HOSTNAME
              GEN3_DB_HOSTNAME|-value: ""-|
            - name: DB_NAME
              GEN3_DB_NAME|-value: "atlas_default"-|
            - name: DB_USERNAME
              GEN3_DB_USERNAME|-value: "atlas_default"-|
            - name: DB_PASSWORD
              GEN3_DB_PASSWORD|-value: ""-|
            - name: DB_ENGINE
              GEN3_DB_ENGINE|-value: "postgres"-|
            - name: DB_PORT
              GEN3_DB_PORT|-value: "5432"-|                                                        
            - name: JENKINS_HOME
              value: "devterm"
            - name: GEN3_HOME
              value: /home/ubuntu/cloud-automation
          command: [ "/bin/bash" ]
          args:
            - "-c"
            - |
              echo "y" | gen3 db reset "atlas" --force
              echo "y" | gen3 db reset "omop" --force
              g3k_kv_filter ${GEN3_HOME}/files/ohdsi/test_data_atlas.sql DB_HOSTNAME "$DB_HOSTNAME" DB_NAME "$DB_NAME" DB_USERNAME "$DB_USERNAME" DB_PASSWORD "$DB_PASSWORD" DB_ENGINE "$DB_ENGINE" DB_PORT "$DB_PORT" > $XDG_RUNTIME_DIR/test_data_atlas.sql
              gen3 psql atlas -f $XDG_RUNTIME_DIR/test_data_atlas.sql
              gen3 psql atlas -f cloud-automation/files/ohdsi/ddl_atlas.sql
              gen3 psql omop -f cloud-automation/files/ohdsi/ddl_results_and_cdm.sql
              gen3 psql omop -f cloud-automation/files/ohdsi/test_data_results_and_cdm.sql            

      restartPolicy: Never
