apiVersion: batch/v1
kind: Job
metadata:
  name: dbgapsync
spec:
  # not yet supported - backOffLimit: 3
  template:
    spec:
      serviceAccountName: useryaml-job
      volumes:
        - name: config-volume
          secret:
            secretName: "fence-secret"
        - name: json-secret-volume
          secret:
            secretName: "fence-json-secret"
        - name: fence-ssh-keys
          secret:
            secretName: "fence-ssh-keys"
        - name: fence-sshconfig
          configMap:
            name: "fence-sshconfig"
        - name: projects
          configMap:
            name: "projects"
        - name: user-dir
          configMap:
            name: "user-dir"
      containers:
      - name: fence
        image: quay.io/cdis/fence:feat_dbgap_syncing
        imagePullPolicy: Always
        env:
          - name: PYTHONPATH
            value: /var/www/fence
        lifecycle:
          postStart:
            exec:
              command:
                - bash
                - -c
                - cp /fence/ssh-keys/..data/* /root/.ssh/ && chmod 400 /root/.ssh/id_rsa /root/.ssh/id_rsa.pub
        volumeMounts:
          - name: "config-volume"
            readOnly: true
            mountPath: "/var/www/fence/local_settings.py"
            subPath: local_settings.py
          - name: "json-secret-volume"
            readOnly: true
            mountPath: "/var/www/fence/fence_credentials.json"
            subPath: fence_credentials.json
          - name: "fence-ssh-keys"
            readOnly: true
            mountPath: "/fence/ssh-keys"
          - name: "fence-sshconfig"
            mountPath: "/root/.ssh/config"
            subPath: "config"
          - name: "projects"
            mountPath: "/var/www/fence/projects.yaml"
            subPath: "projects.yaml"
          - name: "user-dir"
            mountPath: "/var/www/fence/userDir"
        command: ["/bin/bash" ]
        args: 
          - "-c" 
          - |
            fence-create sync-dbgap --projects /var/www/fence/projects.yaml --is_sync True --yaml_dir /var/www/fence/userDir
      restartPolicy: Never
