apiVersion: batch/v1
kind: Job
metadata:
  name: dcf-bucket-replication#PLACEHOLDER#
spec:
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      serviceAccountName: sa-#SA_NAME_PLACEHOLDER#
      volumes:
        - name: cred-volume
          secret:
            secretName: "dcfbucketreplicate-g3auto"
      containers:
      - name: aws-dcf-bucket-replicate
        GEN3_AWS-BUCKET-MANIFEST_IMAGE|-image: quay.io/cdis/dcf-aws-bucket-replicate:dcf-bucket-duplicate-|
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: REGION
          GEN3_REGION|-value: "us-east-1"-|
        - name: SOURCE_BUCKET
          GEN3_SOURCE_BUCKET
        - name: MANIFEST
          GEN3_MANIFEST
        - name: MAPPING
          GEN3_MAPPING
        - name: JOB_QUEUE
          GEN3_JOB_QUEUE
        - name: JOB_DEFINITION
          GEN3_JOB_DEFINITION
        volumeMounts:
          - name: "cred-volume"
            mountPath: "/dcf-bucket-replicate/creds.json"
            subPath: "creds.json"
        resources:
          limits:
            cpu: 1
            memory: 1Gi
        command: ["/bin/bash" ]
        args:
          - "-c"
          - |
            python batch_jobs/bin/run_dcf_bucket_replicate_job.py dcf-replicate-bucket --source_bucket $SOURCE_BUCKET --manifest $MANIFEST --mapping $MAPPING --job_queue ${JOB_QUEUE} --job_definition ${JOB_DEFINITION}
            echo "All done - exit status $?"
      restartPolicy: Never
