apiVersion: batch/v1
kind: Job
metadata:
  name: simdata
spec:
  # not yet supported - backOffLimit: 3
  template:
    spec:
      serviceAccountName: useryaml-job
      volumes:
        - name: api-secret
          secret:
            secretName: "api-secret"
      containers:
      - name: fence
        image: quay.io/cdis/auto-qa:feat_gen_test_data
        imagePullPolicy: Always
        env:
          - name: PYTHONPATH
            value: /var/www/fence
          - name: DICTIONARY_REPOS
            valueFrom:
              configMapKeyRef:
                name: global
                key: dictionary_repos
          - name: TEST_PROJECT
            valueFrom:
              configMapKeyRef:
                name: global
                key: test_project
          - name: SUBMISSION_HOST
            valueFrom:
              configMapKeyRef:
                name: global
                key: submission_host

        volumeMounts:
          - name: "api-secret"
            mountPath: "/var/www/AUTO-QA/credentials.json"
            subPath: "credentials.json"
        command: ["/bin/bash" ]
        args: 
          - "-c" 
          - |
            mkdir -p /AUTO-QA/python-scripts/sim-data-code/TestData
            Rscript /AUTO-QA/python-scripts/sim-data-code/GenTestDataCmd.R $(DICTIONARY_REPOS) develop $(TEST_PROJECT) 100 FALSE TRUE /AUTO-QA/python-scripts/sim-data-code/TestData/
            python scripts.py data-create --host $(SUBMISSION_HOST) --dir /AUTO-QA/python-scripts/sim-data-code/TestData/ --project "$(TEST_PROJECT)" --authfile /var/www/AUTO-QA/credentials.json
      restartPolicy: Never
