apiVersion: batch/v1
kind: Job
metadata:
  name: useryaml
spec:
  template:
    spec:
      serviceAccountName: useryaml-job
      volumes:
        - name: config-volume
          secret:
            secretName: "fence-secret"
        - name: json-secret-volume
          secret:
            secretName: "fence-json-secret"
        - name: fence-jwt-keys
          secret:
            secretName: "fence-jwt-keys"
        - name: fence-yaml
          configMap:
            name: fence
        - name: cert-volume
          secret:
            secretName: "cert-fence-service"
        - name: ca-volume
          secret:
            secretName: "service-ca"
      containers:
      - name: useryaml
        image: quay.io/cdis/fence:master
        volumeMounts:
          - name: "config-volume"
            readOnly: true
            mountPath: "/var/www/fence/local_settings.py"
            subPath: local_settings.py
          - name: "json-secret-volume"
            readOnly: true
            mountPath: "/var/www/fence/fence_credentials.json"
            subPath: fence_credentials.json
          - name: "fence-yaml"
            mountPath: "/var/www/fence/user.yaml"
            subPath: user.yaml
          - name: "cert-volume"
            readOnly: true
            mountPath: "/mnt/ssl/service.crt"
            subPath: "service.crt"
          - name: "cert-volume"
            readOnly: true
            mountPath: "/mnt/ssl/service.key"
            subPath: "service.key"
          - name: "ca-volume"
            readOnly: true
            mountPath: "/mnt/ssl/cdis-ca.crt"
            subPath: "ca.pem"
          - name: "fence-jwt-keys"
            readOnly: true
            mountPath: "/fence/keys"
        command: ["/bin/bash" ]
        args: 
          - "-c" 
          - |
            fence-create create /var/www/fence/user.yaml
      restartPolicy: Never
