kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: useryaml-binding
spec:
  # not yet supported - backOffLimit: 3
  template:
    metadata:
      labels:
        app: gen3job
subjects:
- kind: ServiceAccount
  name: useryaml-job
  apiGroup: ""
roleRef:
  kind: Role
  name: devops
  apiGroup: ""

