apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: selenium-hub
  name: selenium-hub
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      prometheus.io/path: /metrics
      prometheus.io/port: "8080"
      prometheus.io/scrape: "true"
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - env:
          value: "42"
        - name: GRID_BROWSER_TIMEOUT
          value: "0"
        image: selenium/hub:4
        imagePullPolicy: Always
        name: hub
        ports:
        - containerPort: 4444
          protocol: TCP
        - containerPort: 4442
          protocol: TCP
        - containerPort: 4443
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 4444
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 4444
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5      
      - name: selenium-grid-exporter
        GEN3_SELENIUM_GRID_EXPORTER_IMAGE|-image: registry.hub.docker.com/wakeful/selenium-grid-exporter-|
        args: ["-scrape-uri", "http://127.0.0.1:4444/status"]
        ports:
        - containerPort: 8080
      terminationGracePeriodSeconds: 30
