kind: Service
apiVersion: v1
metadata:
  name: portal-service 
spec:
  selector:
    app: portal 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
      nodePort: 30001 
  type: NodePort
