apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: networkpolicy-pidgin
spec:
  podSelector:
    matchLabels:
      app: pidgin
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: pidgin
      - podSelector:
          matchLabels:
             app: revproxy
      ports:
         - port: 80
         - port: 443

  policyTypes:
   - Ingress
   - Egress
