#
# Note: apply this file via apply_config to fill in the DNS
#   resolver required for cookie-based routing to canary/test services
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: revproxy-nginx-conf
  namespace: default 
data:
  nginx.conf: |
      user www-data;
      worker_processes 4;
        
      pid /run/nginx.pid;
      
      events {
      	worker_connections 768;
      	# multi_accept on;
      }
      
      http {
      
      	##
      	# Basic Settings
      	##   
      	sendfile on;
      	tcp_nopush on;
      	tcp_nodelay on;
      	keepalive_timeout 65;
      	types_hash_max_size 2048;
      	# server_tokens off;
      
      	# server_names_hash_bucket_size 64;
      	# server_name_in_redirect off;
      
      	include /etc/nginx/mime.types;
      	default_type application/octet-stream;
      
      	##
      	# Logging Settings
      	##
        log_format aws   '$http_x_forwarded_for - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent"';
      	access_log /dev/stdout aws;
      	error_log /dev/stderr;
      
      	##
      	# Gzip Settings
      	##
        gzip on;
        gzip_disable "msie6";
        gzip_types application/javascript;
      
        ##
      	# Proxy Settings
      	##
      	server {
      		listen 80;
      		server_tokens off;
      		add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
      		add_header X-Frame-Options "SAMEORIGIN";
      		if ($http_x_forwarded_proto = "http") { rewrite ^/(.*)$ https://$host$request_uri permanent; }
          # DNS resolver required to resolve dynamic hostnames, btw - kubedns may not support ipv6
          resolver kube-dns.kube-system.svc.cluster.local ipv6=off;
          
          set $access_token "";
          set $csrf_check "ok-tokenauth";
          if ($cookie_access_token) {
              set $access_token "bearer $cookie_access_token";
              # cookie auth requires csrf check
              set $csrf_check "fail";
          }
          if ($http_authorization) {
              # Authorization header is present - prefer that token over cookie token
              set $access_token "$http_authorization";
          }

          #
          # Note - need to repeat this line in location blocks that call proxy_set_header,
          #   as nginx proxy module inherits proxy_set_header if and only if current level does
          #   not set headers ... http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header
          #
          proxy_set_header   Authorization "$access_token";
          proxy_set_header   X-Forwarded-For "$http_x_forwarded_for";
          #add_header X-debug-auth "$access_token"; #- only do this for quick and dirty client-side debugging
          
          #
          # CSRF check
          # This block requires a csrftoken for all POST requests.
          #
          if ($cookie_csrftoken = $http_x_csrf_token) {
            # this will fail further below if cookie_csrftoken is empty
            set $csrf_check "ok-$cookie_csrftoken";
          }
          if ($request_method != "POST") {
            set $csrf_check "ok-$request_method";
          }
          if ($cookie_access_token = "") {
            # do this again here b/c empty cookie_csrftoken == empty http_x_csrf_token - ugh  
            set $csrf_check "ok-tokenauth";
          }
          if ($csrf_check !~ ^ok-\S.+$) {
            return 403 "failed csrf check";
          }
          
          location / {
              set $portal_service http://portal-service.default.svc.cluster.local;
              if ($cookie_portal_service ~ ^[\w-]+$) {
                  # support accessing portal-service in another k8s namespace
                  set $portal_service http://portal-service.$cookie_portal_service.svc.cluster.local;
                  add_header X-debug-portal "$portal_service" always;
              }
              if ($cookie_csrftoken = "") {
                add_header Set-Cookie "csrftoken=$request_id$request_length$request_time$time_iso8601;Path=/";
              }
              
              proxy_pass $portal_service;
          }
          location /index {
              if ($cookie_csrftoken = "") {
                add_header Set-Cookie "csrftoken=$request_id$request_length$request_time$time_iso8601;Path=/";
              }
              proxy_pass http://indexd-service/;
          }
          location /user {
              if ($cookie_csrftoken = "") {
                add_header Set-Cookie "csrftoken=$request_id$request_length$request_time$time_iso8601;Path=/";
              }
              proxy_pass http://fence-service/;
          }
          location /api/v0/submission/getschema {
              if ($cookie_csrftoken = "") {
                add_header Set-Cookie "csrftoken=$request_id$request_length$request_time$time_iso8601;Path=/";
              }
              proxy_next_upstream off;
              proxy_pass http://peregrine-service/v0/submission/getschema;
          }
          location /api/v0/submission/graphql {
              if ($cookie_csrftoken = "") {
                add_header Set-Cookie "csrftoken=$request_id$request_length$request_time$time_iso8601;Path=/";
              }
              proxy_next_upstream off;
              # Forward the host and set Subdir header so api
              # knows the original request path for hmac signing
              proxy_set_header   Host $host;
              proxy_set_header   Subdir /api;
              proxy_set_header   Authorization "$access_token";
              proxy_set_header   X-Forwarded-For "$http_x_forwarded_for";
              proxy_connect_timeout 300;
              proxy_send_timeout 300;
              proxy_read_timeout 300;
              send_timeout 300;
              proxy_pass http://peregrine-service/v0/submission/graphql;
          }
          location /api {
              if ($cookie_csrftoken = "") {
                add_header Set-Cookie "csrftoken=$request_id$request_length$request_time$time_iso8601;Path=/";
              }
              proxy_next_upstream off;
              # Forward the host and set Subdir header so api
              # knows the original request path for hmac signing
              proxy_set_header   Host $host;
              proxy_set_header   Subdir /api;
              proxy_set_header   Authorization "$access_token";
              proxy_set_header   X-Forwarded-For "$http_x_forwarded_for";
              proxy_connect_timeout 300;
              proxy_send_timeout 300;
              proxy_read_timeout 300;
              send_timeout 300;
              proxy_pass http://sheepdog-service/;
              #proxy_pass http://gdcapi-service/;
          }
      	}
      }
