kind: Service
apiVersion: v1
metadata:
  name: userapi-service
spec:
  selector:
    app: userapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
      nodePort: 30003 
  type: NodePort

