apiVersion: batch/v1
kind: CronJob
metadata:
  name: useryaml
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        containers:
        - name: useryaml
          image: quay.io/cdis/fence:master
          command: ["/bin/bash" ]
          args: 
            - "-c" 
            - |
              echo "downloading $userYamlS3Path";
              aws s3 cp $userYamlS3Path /tmp/user.yaml;
              fence-create create /tmp/user.yaml;
              kubectl delete configmap fence
              kubectl create configmap fence --from-file=/tmp/user.yaml" 
          env:
          - name: userYamlS3Path
            valueFrom:
                configMapKeyRef:
                  name: global
                  key: useryaml_s3path
        restartPolicy: Never
  