---
- name: Apply CIS Linux 2 Benchmark
  hosts: ec2-ubuntu-host
  gather_facts: yes
  tasks:
    - name: 1.1.1 Ensure mounting of cramfs filesystems is disabled
      mount:
        name: cramfs
        fstype: cramfs
        state: unmounted
        enabled: no

    - name: 1.1.2 Ensure mounting of freevxfs filesystems is disabled
      mount:
        name: freevxfs
        fstype: freevxfs
        state: unmounted
        enabled: no

    # Add tasks for other recommendations in the benchmark

    - name: 5.1.8 Ensure at/cron is restricted to authorized users
      file:
        path: /etc/cron.deny
        state: absent
      become: yes
      become_method: sudo

    - name: 5.2.1 Ensure permissions on /etc/crontab are configured
      file:
        path: /etc/crontab
        mode: '0600'
        owner: root
        group: root
      become: yes
      become_method: sudo

