kind: Service
apiVersion: v1
metadata:
  name: redis-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      ambassador_id: "gen3"
      kind:  Mapping
      name:  redis_mapping
      service: http://redis-service:6379
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: redis
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: NodePort
