kind: Service
apiVersion: v1
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: NodePort
