apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: portal-deployment
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
      - name: portal
        image: quay.io/cdis/data-portal:master 
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: cdis-devservices-pull-secret
