apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sheepdog-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: sheepdog
    spec:
      volumes:
        - name: config-volume
          secret:
            secretName: "sheepdog-secret"
        - name: cert-volume
          secret:
            secretName: "cert-sheepdog-service"
        - name: ca-volume
          secret:
            secretName: "service-ca"
      containers:
        - name: sheepdog
          image: quay.io/cdis/sheepdog:feat_deployment
          livenessProbe:
            httpGet:
              path: /_status
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          ports:
          - containerPort: 80
          - containerPort: 443
          volumeMounts:
            - name: "config-volume"
              readOnly: true
              mountPath: "/var/www/sheepdog/wsgi.py"
              subPath: "wsgi.py"
            - name: "cert-volume"
              readOnly: true
              mountPath: "/mnt/ssl/service.crt"
              subPath: "service.crt"
            - name: "cert-volume"
              readOnly: true
              mountPath: "/mnt/ssl/service.key"
              subPath: "service.key"
            - name: "ca-volume"
              readOnly: true
              mountPath: "/mnt/ssl/cdis-ca.crt"
              subPath: "ca.pem"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 0.8
              memory: 512Mi
      imagePullSecrets:
        - name: cdis-devservices-pull-secret

