---
# pelican deployment - only for testing
# normally use tube via: gen3 job run etl
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xpelican-deployment
spec:
  selector:
    # Only select pods based on the 'app' label
    matchLabels:
      app: xpelican
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: xpelican
        netnolimit: "yes"
        GEN3_DATE_LABEL
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - xpelican
              topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: false
      volumes:
        - name: peregrine-creds-volume
          secret:
            secretName: "peregrine-creds"
        - name: pelican-creds-volume
          secret:
            secretName: "pelican-creds"
      containers:
        - name: xpelican
          imagePullPolicy: Always
          image: "quay.io/cdis/pelican-export:2020.03"
          ports:
          - containerPort: 80
          env:
          - name: DICTIONARY_URL
            valueFrom:
              configMapKeyRef:
                name: manifest-global
                key: dictionary_url
          - name: GEN3_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: manifest-global
                key: hostname
          - name: ROOT_NODE
            value: subject
          volumeMounts:
            - name: "peregrine-creds-volume"
              readOnly: true
              mountPath: "/peregrine-creds.json"
              subPath: creds.json
            - name: "pelican-creds-volume"
              readOnly: true
              mountPath: "/pelican-creds.json"
              subPath: config.json
          resources:
            limits:
              cpu: 1
              memory: 4Gi
          command: ["/bin/bash" ]
          args:
            - "-c"
            - |
              while true; do sleep 5; done
