kind: Service
apiVersion: v1
metadata:
  name: indexd-service
spec:
  selector:
    app: indexd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
      nodePort: 30002 
  type: NodePort

