name: Build AWSHelper Base Images and Push to Quay and ECR

on: 
 push:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      awshelper: ${{ steps.filter.outputs.awshelper }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          awshelper:
            - 'Docker/awshelper/**'

  awshelper:
    needs: changes
    if: ${{ needs.changes.outputs.awshelper == 'true' }}
    runs-on: ubuntu-latest
    name: AwsHelper Build and Push
    steps:
      - uses: actions/checkout@v3
      - uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
        with:
          DOCKERFILE_LOCATION: "./Docker/awshelper/Dockerfile"
          OVERRIDE_REPO_NAME: "awshelper"
        secrets:
          ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
